"""Plain numbered SQL migrations with a ``schema_migrations`` ledger.

Chosen over Alembic on purpose: the DDL here is hand-tuned (partial unique indexes, CHECK
constraints spanning several columns) and reads far better as SQL than as autogenerated
Python. The tradeoff is that migrations are written by hand -- which is the point.

Files are ``NNNN_name.up.sql`` and ``NNNN_name.down.sql``. ``${SCHEMA}`` is substituted with
the configured schema so nothing hardcodes a namespace. Each migration runs inside a single
transaction: it applies completely or not at all.
"""

from __future__ import annotations

import hashlib
import re
from dataclasses import dataclass
from pathlib import Path

from aimternet.config.settings import settings
from aimternet.db.session import connection

MIGRATIONS_DIR = Path(__file__).resolve().parent / "migrations"
_FILENAME = re.compile(r"^(?P<version>\d{4})_(?P<name>[a-z0-9_]+)\.(?P<direction>up|down)\.sql$")


class MigrationError(RuntimeError):
    """A migration is missing, malformed, or failed to apply."""


@dataclass(frozen=True, slots=True)
class Migration:
    version: str
    name: str
    up_path: Path
    down_path: Path

    @property
    def checksum(self) -> str:
        return hashlib.sha256(self.up_path.read_bytes()).hexdigest()

    def sql(self, direction: str, substitutions: dict[str, str]) -> str:
        path = self.up_path if direction == "up" else self.down_path
        text = path.read_text(encoding="utf-8")
        for key, value in substitutions.items():
            text = text.replace("${" + key + "}", value)
        return text


def discover_migrations(directory: Path = MIGRATIONS_DIR) -> list[Migration]:
    ups: dict[str, tuple[str, Path]] = {}
    downs: dict[str, Path] = {}
    for path in sorted(directory.glob("*.sql")):
        match = _FILENAME.match(path.name)
        if match is None:
            raise MigrationError(
                f"migration filename does not follow NNNN_name.(up|down).sql: {path.name}"
            )
        version, name, direction = match["version"], match["name"], match["direction"]
        if direction == "up":
            ups[version] = (name, path)
        else:
            downs[version] = path

    migrations = []
    for version, (name, up_path) in sorted(ups.items()):
        if version not in downs:
            raise MigrationError(
                f"migration {version}_{name} has no .down.sql; rollback must be possible"
            )
        migrations.append(
            Migration(version=version, name=name, up_path=up_path, down_path=downs[version])
        )
    return migrations


def _substitutions(schema: str) -> dict[str, str]:
    """Values injected into migration SQL so nothing hardcodes a namespace or a secret."""
    cfg = settings()
    ro_password = cfg.pg_ro_password.get_secret_value() if cfg.pg_ro_password else ""
    return {
        "SCHEMA": schema,
        "DATABASE": cfg.pg_database,
        "RO_USER": cfg.pg_ro_user,
        "RO_PASSWORD": ro_password,
    }


def _ensure_ledger(conn: object, schema: str) -> None:
    with conn.cursor() as cur:  # type: ignore[attr-defined]
        cur.execute(f'CREATE SCHEMA IF NOT EXISTS "{schema}"')
        cur.execute(
            f"""
            CREATE TABLE IF NOT EXISTS "{schema}".schema_migrations (
                version    TEXT PRIMARY KEY,
                name       TEXT NOT NULL,
                checksum   TEXT NOT NULL,
                applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
            )
            """
        )


def applied_versions(schema: str | None = None) -> dict[str, str]:
    """version -> checksum for everything already applied."""
    schema = schema or settings().pg_schema
    with connection() as conn:
        _ensure_ledger(conn, schema)
        with conn.cursor() as cur:
            cur.execute(f'SELECT version, checksum FROM "{schema}".schema_migrations')
            return dict(cur.fetchall())


def upgrade(target: str | None = None, schema: str | None = None) -> list[str]:
    """Apply every pending migration up to ``target``. Returns what was applied."""
    schema = schema or settings().pg_schema
    migrations = discover_migrations()
    already = applied_versions(schema)

    for migration in migrations:
        recorded = already.get(migration.version)
        if recorded is not None and recorded != migration.checksum:
            raise MigrationError(
                f"migration {migration.version}_{migration.name} was applied with a different "
                f"checksum. Editing an applied migration silently diverges environments; "
                f"write a new migration instead."
            )

    applied: list[str] = []
    for migration in migrations:
        if migration.version in already:
            continue
        with connection() as conn:
            _ensure_ledger(conn, schema)
            with conn.cursor() as cur:
                cur.execute(migration.sql("up", _substitutions(schema)))
                cur.execute(
                    f'INSERT INTO "{schema}".schema_migrations (version, name, checksum) '
                    f"VALUES (%s, %s, %s)",
                    (migration.version, migration.name, migration.checksum),
                )
        applied.append(f"{migration.version}_{migration.name}")
        if target is not None and migration.version == target:
            break
    return applied


def downgrade(steps: int = 1, schema: str | None = None) -> list[str]:
    """Roll back the most recently applied migrations, newest first."""
    schema = schema or settings().pg_schema
    migrations = {m.version: m for m in discover_migrations()}
    already = applied_versions(schema)

    reverted: list[str] = []
    for version in sorted(already, reverse=True)[:steps]:
        migration = migrations.get(version)
        if migration is None:
            raise MigrationError(
                f"migration {version} is recorded as applied but its files are gone"
            )
        with connection() as conn, conn.cursor() as cur:
            cur.execute(migration.sql("down", _substitutions(schema)))
            cur.execute(
                f'DELETE FROM "{schema}".schema_migrations WHERE version = %s', (version,)
            )
        reverted.append(f"{migration.version}_{migration.name}")
    return reverted


def status(schema: str | None = None) -> list[dict[str, object]]:
    schema = schema or settings().pg_schema
    already = applied_versions(schema)
    return [
        {
            "version": m.version,
            "name": m.name,
            "applied": m.version in already,
        }
        for m in discover_migrations()
    ]
