ALTER DEFAULT PRIVILEGES IN SCHEMA ${SCHEMA} REVOKE SELECT ON TABLES FROM ${RO_USER};
REVOKE ALL ON ALL TABLES IN SCHEMA ${SCHEMA} FROM ${RO_USER};
REVOKE ALL ON SCHEMA ${SCHEMA} FROM ${RO_USER};
REVOKE ALL ON DATABASE ${DATABASE} FROM ${RO_USER};
DROP ROLE IF EXISTS ${RO_USER};
